import {anchors,caseContract,funnel,latest,lateUpdateShare,money,number,onboardingTotal,percent,reportOpenRate,supportMinutes,supportTotal} from './data'
const service=latest.window+' · service-month (ngày tham gia đã đến hạn)'
const created=latest.window+' · booking-created month (ngày tạo đơn)'
export const dictionary=[
 ['Chỗ hoàn thành',number(latest.completed),'seat',service,'Chỗ đã đặt, scheduled service date trong tháng và đã đến hạn','Sum completed trong serviceRows theo price buckets','Synthetic bổ sung','Đã tham gia và ghi nhận; hủy/no-show/pending không tính.'],
 ['Đơn được tạo và chỗ trong đơn',number(latest.bookings)+' bookings · '+number(latest.createdSeats)+' seats','booking / seat',created,'Đơn tạo thành công trong tháng','creationRows: đếm booking events và seats trong các đơn','Synthetic bổ sung','Một đơn nhiều chỗ; ngày tham gia có thể khác tháng tạo. Không reconcile với cohort ngày dịch vụ.'],
 ['Studios có chỗ hoàn thành',number(latest.completedStudios),'studio',service,'Studio có ít nhất một completed seat trong tháng','Distinct studio count trong periods, không sum qua tháng','Synthetic bổ sung','Không có raw studio IDs hoặc total registered/active; không tính activation rate.'],
 ['Trạng thái chỗ đã đến hạn',number(latest.booked)+' booked seats','seat / % seats',service,'Mọi chỗ đặt xác nhận với service date trong tháng; đã đến hạn ở cutoff','Completed + cancelled + noShow + pending = booked. Rate mỗi status = status seats / booked seats','Synthetic bổ sung; 180 chỗ hủy tháng mới nhất giữ P2-B','Các statuses loại trừ nhau. Pending là đã đến hạn chưa phân loại; không phải future seats.'],
 ['Funnel trên trang studio',percent(funnel.at(-1).fromStart)+' tạo đơn','journey / % journeys',created+'; follow-up 7 ngày','journey_id vào một trang studio trong tháng, cùng cohort mọi bước','Unique journey theo bước thứ tự; một journey tối đa một booking. Tỷ lệ từ đầu = bước / Visit; chuyển tiếp = bước / bước trước','Synthetic bổ sung','Journey là session, không phải unique customer. Không có tìm kiếm nhiều studios. Dataset giả định các booking creations nằm trong cohort và cùng tháng entry; không có đơn ngoài cohort hoặc tạo sang tháng sau. Không suy rộng giả định này cho dữ liệu thật.'],
 ['Studios chưa hoàn tất onboarding',number(onboardingTotal)+' = '+number(anchors.onboarding.awaitingApproval)+' + '+number(anchors.onboarding.approvedWithoutCalendar),'studio','Snapshot sau ba tháng','48 studios chưa hoàn tất onboarding','Chưa duyệt hồ sơ + đã duyệt chưa có lịch; hai nhóm loại trừ','P2-A','Chưa biết nhu cầu đặt chỗ hoặc total studios; không coi H03 tự xử lý cả 48.'],
 ['Chỗ hủy liên quan cập nhật muộn',number(anchors.cancellation.lateUpdateRelatedSeats)+'/'+number(anchors.cancellation.cancelledSeats)+' · '+percent(lateUpdateShare),'seat / % cancelled seats','Tháng gần nhất; ánh xạ Tháng 3','180 cancelled seats','90 có liên quan cập nhật muộn / 180 chỗ hủy','P2-B','Không phải 90 chỗ có thể cứu; chưa chứng minh root cause. Phần còn lại chưa có phân loại nguyên nhân.'],
 ['Studios mở H04',number(anchors.studioReport.opened)+'/'+number(anchors.studioReport.tracked)+' · '+percent(reportOpenRate),'studio / % tracked studios','Tháng gần nhất','72 studios trong tập theo dõi H04','Distinct studios mở H04 ít nhất một lần / 72','P2-C','Không phải total active/registered. Không suy ra 48+72; chưa biết các tập overlap. Interview không có sample size; email vẫn dùng.'],
 ['Khách đặt lại (context)',percent(latest.repeatRate),'% customers',created,'Unique customers tạo booking trong tháng','Khách có booking tạo trước đầu tháng / customers trong tháng','Synthetic bổ sung','Không phải retention cohort 30d; đặt lại chưa đồng nghĩa tham gia hay tăng chỗ hoàn thành.'],
 ['Đơn / khách',new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2}).format(latest.bookingsPerCustomer),'bookings / customer',created,'Unique customers có tạo booking trong tháng','Booking events / customers','Synthetic bổ sung','Average che giấu phân bố. Không dùng seats thay booking count.'],
 ['Booked GMV',money(latest.bookedGMV),'VND',created,'Chỗ thuộc các đơn tạo trong tháng, theo giá tại lúc đặt','Gross booked value aggregate trong creationRows','Synthetic bổ sung','Trước hủy/refund; có thể phục vụ tháng khác. Không phải completed-service value, revenue hay profit.'],
 ['Giá trị dịch vụ hoàn thành',money(latest.completedValue),'VND',service,'Completed seats trong service-month','Sum completed seats × price từng bucket trong serviceRows','Synthetic bổ sung','Giá khác nhau theo bucket; 300.000 ₫ chỉ tham chiếu, không áp cho mọi seat.'],
 ['Doanh thu phí Hẹn',money(latest.revenue),'VND',service,'Giá trị chỗ hoàn thành đã ghi nhận; giả định chỉ có nguồn phí này',percent(caseContract.feeRate*100)+' × completed-service value','Fee từ case contract; value synthetic bổ sung','Trước chi phí thanh toán/vận hành. Không tính phí trên booked GMV, hủy, no-show hoặc pending; không phải profit.'],
 ['Câu hỏi qua nhân viên',number(supportTotal)+' tickets · '+number(supportMinutes)+' phút','ticket / phút',latest.window+' · theo ngày tạo ticket','Tickets được ghi nhận trong tháng','Một primary category/ticket; sum counts; share = category/total. Minutes là tổng active handling time','P2-B xác nhận có câu hỏi; counts/phân loại/minutes đều synthetic bổ sung','Chưa biết customers/bookings liên quan hoặc eligibility đổi buổi. Không có ticket rate; thời gian xử lý không phải chi phí tiền hoặc công xây chức năng.'],
 ['So sánh tháng trước','Tháng 3 so với Tháng 2','% thay đổi / pp','Hai tháng không chồng lấn; convention theo từng metric','Cùng định nghĩa mỗi metric qua các tháng','% change = (kỳ này / kỳ trước − 1) × 100. pp = rate kỳ này − rate kỳ trước','Derived từ canonical inputs','Baseline 0 trả về Chưa đo, không chia 0. Không tự chứng minh nguyên nhân hoặc mức cải thiện của thay đổi.']
].map(([name,value,unit,period,population,aggregation,source,limit],i)=>({id:i,name,value,unit,period,population,aggregation,source,limit}))
