import {test,expect} from '@playwright/test'
const studentForbidden=/\b(Reach|Impact|Confidence|Urgency|Effort|RICE|WSJF)\b|Mộc|P3-|P4-|Phase 4|priority badge|marketplace discovery/i
async function verifyStudentText(page){
 const text=await page.locator('body').evaluate(el=>el.textContent+' '+Array.from(el.querySelectorAll('*')).map(n=>[n.getAttribute('aria-label'),n.getAttribute('title'),n.getAttribute('alt')].filter(Boolean).join(' ')).join(' '))
 expect(text).not.toMatch(studentForbidden)
 await expect(page.getByText('Logic 0.1 và mapping cuối buổi',{exact:true})).toHaveCount(0)
}
for(const width of [1440,390]){
 test('student evidence, cohorts, charts and guide at '+width+'px',async({page})=>{
  await page.setViewportSize({width,height:1000})
  const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(['error','warning'].includes(m.type()))errors.push(m.text())})
  await page.goto('/');await expect(page).toHaveTitle('Hẹn Analytics')
  await expect(page.getByRole('heading',{name:'Kết quả vận hành Hẹn',exact:true})).toBeVisible()
  await expect(page.locator('.recharts-surface')).toHaveCount(5)
  const evidence=page.locator('#evidence')
  await expect(evidence).toContainText('48 studios')
  await expect(evidence).toContainText('28 chưa duyệt hồ sơ; 20 đã duyệt nhưng chưa có lịch')
  await expect(evidence).toContainText('180 chỗ hủy');await expect(evidence).toContainText('90 chỗ liên quan')
  await expect(evidence).toContainText('9/72 studios');await expect(evidence).toContainText('12,5%')
  await expect(evidence.getByText(/High|Medium|Low|priority/i)).toHaveCount(0)
  await expect(page.getByRole('button',{name:'Định nghĩa Chỗ hoàn thành',exact:true})).toHaveAttribute('title',/service-month.*seat/)
  await verifyStudentText(page)
  await expect(page.locator('vite-error-overlay')).toHaveCount(0)
  const chart=page.locator('.recharts-wrapper').first()
  await chart.scrollIntoViewIfNeeded();const box=await chart.boundingBox()
  await page.mouse.move(box.x+box.width*0.65,box.y+box.height*0.4)
  await expect(chart.locator('.recharts-tooltip-wrapper')).toBeVisible()
  await expect(chart.locator('.recharts-tooltip-wrapper')).toContainText('Chỗ hoàn thành')
  await page.getByRole('link',{name:'P2-A/B/C',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Ba vùng evidence của Buổi 2',exact:true})).toBeInViewport()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/p2-dashboard-'+width+'.png',fullPage:true})
  await page.getByRole('tab',{name:'Hướng dẫn',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Cách đọc dữ liệu Hẹn',exact:true})).toBeVisible()
  const details=page.locator('details')
  await expect(details).toHaveCount(15)
  await details.evaluateAll(elements=>elements.forEach(el=>el.open=true))
  await verifyStudentText(page)
  await expect(page.locator('#dictionary')).toContainText('Không phải 90 chỗ có thể cứu')
  await expect(page.locator('#dictionary')).toContainText('8% × completed-service value')
  await expect(page.locator('#dictionary')).toContainText('29.216.000 ₫')
  await expect(page.locator('#dictionary')).toContainText('không sum qua tháng')
  await page.getByRole('link',{name:'Đọc hành trình',exact:true}).click()
  await expect(page.getByRole('heading',{name:'3. Đọc hành trình và kết quả tham gia',exact:true})).toBeInViewport()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/p2-guide-'+width+'.png',fullPage:true})
  await page.getByRole('tab',{name:'Hướng dẫn',exact:true}).focus();await page.keyboard.press('ArrowLeft')
  await expect(page.getByRole('tab',{name:'Dashboard',exact:true})).toBeFocused()
  await expect(page.getByRole('heading',{name:'Kết quả vận hành Hẹn',exact:true})).toBeVisible()
  expect(errors).toEqual([])
 })
 test('facilitator stays out of student DOM at '+width+'px',async({page})=>{
  await page.setViewportSize({width,height:1000});await page.goto('/')
  await page.getByRole('tab',{name:'Facilitator',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Điều phối Buổi 2',exact:true})).toHaveCount(0)
  await page.getByLabel('Password',{exact:true}).fill('incorrect-password')
  await page.getByRole('button',{name:'Đăng nhập',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('Password không đúng')
  await expect(page.getByLabel('Password',{exact:true})).toHaveValue('')
  if(process.env.HEN_FACILITATOR_PASSWORD){
   await page.getByLabel('Password',{exact:true}).fill(process.env.HEN_FACILITATOR_PASSWORD)
   await page.getByRole('button',{name:'Đăng nhập',exact:true}).click()
   await expect(page.getByRole('heading',{name:'Điều phối Buổi 2',exact:true})).toBeVisible()
   await expect(page.getByText('Logic 0.1 và mapping cuối buổi',{exact:true})).toBeVisible()
   await page.getByRole('button',{name:'Khóa lại',exact:true}).click()
   await expect(page.getByRole('button',{name:'Đăng nhập',exact:true})).toBeVisible()
  }
  await page.getByRole('tab',{name:'Dashboard',exact:true}).click();await verifyStudentText(page)
  await page.getByRole('tab',{name:'Hướng dẫn',exact:true}).click();await verifyStudentText(page)
 })
}
