import {Card,CardContent,CardHeader,CardTitle} from './ui/card'
import {dictionary} from '../lib/dictionary'
import {caseContract,funnel,latest,money,number,percent} from '../lib/data'
export default function DataGuide(){
 return <div className="space-y-8 text-sm leading-7">
 <div className="rounded-2xl bg-slate-950 p-6 text-white"><h1 className="text-3xl font-semibold">Cách đọc dữ liệu Hẹn</h1><p className="mt-4 text-slate-300">Tra cứu đơn vị, kỳ đo và giới hạn các quan sát. Số đã được tính sẵn. Hẹn là phần mềm cho trang đặt chỗ riêng của mỗi studio.</p></div>
 <nav aria-label="Mục hướng dẫn" className="flex flex-wrap gap-2">{[['units','Đơn vị & kỳ đo'],['dictionary','Tra cứu chỉ số'],['funnel-guide','Đọc hành trình']].map(([id,label])=><a key={id} href={'#'+id} className="rounded-lg border bg-white px-4 py-2">{label}</a>)}</nav>
 <section id="units" className="scroll-mt-36 space-y-4"><h2 className="text-xl font-semibold">1. Đơn vị và kỳ đo</h2><div className="grid gap-4 md:grid-cols-2">{[
 ['Studio, customer, booking, seat','Studio tổ chức buổi; customer đặt chỗ; booking là đơn; seat là một chỗ tham gia. Một đơn có nhiều chỗ, một khách có thể nhiều đơn. Không cộng các đơn vị này.'],
 ['Tạo đơn và tham gia','Booking created là tạo đơn thành công. Completed seat là chỗ đã tham gia và ghi nhận; hủy/no-show/pending không phải completed.'],
 ['Hai convention kỳ đo','Booking-created month tính theo ngày tạo đơn; service-month theo ngày tham gia đã đến hạn. Các tháng không chồng lấn; không reconcile hai populations khác ngày đo.'],
 ['Tỷ lệ và thay đổi','Rate cần denominator. % thay đổi so tháng trước khác chênh lệch hai tỷ lệ (pp). Các số đã tính sẵn, không cần tính lại để đọc trang.'],
 ['Chưa biết không phải số 0','Demand của 48 studios, total registered, eligibility đổi buổi chưa có số liệu. Không lấy số khác lấp khoảng trống.'],
 ['Nguồn và giới hạn','P2-A/B/C là anchors từ thẻ gốc. Trend, funnel, ngày và giá là synthetic bổ sung. Quan sát liên quan chưa chứng minh nguyên nhân hoặc hiệu quả của thay đổi.']
 ].map(([title,text])=><Card key={title}><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent>{text}</CardContent></Card>)}</div></section>
 <section id="dictionary" className="scroll-mt-36 space-y-4"><h2 className="text-xl font-semibold">2. Tra cứu chỉ số</h2><p>Giá trị kỳ mới nhất; mở thẻ để xem population, aggregation, nguồn và giới hạn. Không có target hoặc benchmark thị trường trên dashboard.</p>{dictionary.map(row=><details key={row.id} className="rounded-xl border bg-white"><summary className="cursor-pointer p-4 font-medium">{row.name}<span className="ml-3 text-blue-700">{row.value}</span></summary><dl className="grid gap-3 border-t p-5 sm:grid-cols-[140px_1fr]">{[['Nguồn',row.source],['Đơn vị',row.unit],['Kỳ đo',row.period],['Population',row.population],['Cách tổng hợp',row.aggregation],['Giới hạn kết luận',row.limit]].map(([label,text])=><div key={label} className="contents"><dt className="font-semibold">{label}</dt><dd className="m-0">{text}</dd></div>)}</dl></details>)}</section>
 <section id="funnel-guide" className="scroll-mt-36 space-y-4"><h2 className="text-xl font-semibold">3. Đọc hành trình và kết quả tham gia</h2><Card><CardContent className="space-y-3 p-5"><p>Cùng journey cohort vào trang studio trong {latest.window}, follow-up 7 ngày: {funnel.map(s=>s.label+': '+number(s.count)).join(' → ')}.</p><p>Tạo đơn từ lúc vào trang: <strong>{percent(funnel.at(-1).fromStart)}</strong>. Chọn slot từ xem lịch: <strong>{percent(funnel[2].fromPrevious)}</strong>. Hai tỷ lệ có denominator khác nhau.</p><p>Drop-off có thể do lịch, thông tin, giá hoặc nhu cầu; chưa có dữ liệu phân biệt nguyên nhân. Journey là session trên trang của một studio.</p><p>Cohort post-booking khác: {number(latest.booked)} booked seats có service date tháng này, đã đến hạn. {number(latest.completed)} hoàn thành; {number(latest.cancelled)} hủy; {number(latest.noShow)} no-show; {number(latest.pending)} chờ ghi nhận. Không dùng số đơn funnel làm denominator.</p><p>Phí = {percent(caseContract.feeRate*100)} × {money(latest.completedValue)} giá trị hoàn thành = <strong>{money(latest.revenue)}</strong>. Trước chi phí; không phải profit và không thu trên booked GMV.</p></CardContent></Card></section>
 </div>
}
