import { Card, CardContent, CardHeader, CardTitle } from './ui/card'
function Block({ title, children }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="space-y-3 text-sm leading-7">{children}</CardContent></Card> }
function Rows({ heads, rows }) { return <div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-100"><tr>{heads.map(x => <th key={x} className="p-4">{x}</th>)}</tr></thead><tbody>{rows.map((r,i) => <tr key={i} className="border-t bg-white">{r.map((x,j) => <td key={j} className="p-4 align-top leading-7">{x}</td>)}</tr>)}</tbody></table></div> }
function Section({ id, title, children }) { return <section id={id} className="scroll-mt-36 space-y-4"><h2 className="text-xl font-semibold">{title}</h2>{children}</section> }
const dimensionRows = [
 ['Reach','Ai gặp vấn đề và bao nhiêu người có thể hưởng lợi trong window của initiative?','Dùng 18.420 bookings làm Reach của mọi feature.','Tách events khỏi people; xác định eligible segment, tần suất và coverage. Không có raw counts thì ghi unknown hoặc range có căn cứ.'],
 ['Impact / Value','Outcome nào thay đổi, mức thay đổi kỳ vọng và vì sao initiative có thể tác động?','Drop-off lớn nên feature chắc chắn có Impact cao.','Drop-off là quy mô cơ hội, không phải uplift. Yêu cầu causal hypothesis; phân biệt cải thiện tương đối với pp và tác động tới business.'],
 ['Confidence','Ta chắc về phép đo, nguyên nhân hay giải pháp?','Analytics High nên Confidence của AI cũng High.','Tách measurement / diagnosis / solution evidence. Interviews giúp tìm nguyên nhân, experiment giúp đánh giá hiệu quả; không đổi nhãn evidence thành score máy móc.'],
 ['Urgency / Cost of Delay','Trì hoãn một kỳ gây mất gì hoặc bỏ lỡ cơ hội nào?','Chỉ số xấu hoặc giảm nhanh tự động là urgent nhất.','Kiểm tra xu hướng cùng scope, thiệt hại theo thời gian và deadline thật. Không có baseline chi phí thì không tự tính tiền mất đi.'],
 ['Effort / Feasibility','Để tạo outcome cần engineering, vận hành, dependency và constraints nào?','68% manual reschedule tương đương effort triển khai lớn.','Manual rate là workload hiện tại. Dùng CU/estimate và dependency từ initiative cards được phát; không tự cấp effort từ dashboard.'],
]
const scenarios = [
 ['Booking tăng, cancellation tăng','Observation: volume và cancellation cùng tăng. Hypotheses: traffic ít cam kết, supply quá tải hoặc thiếu slot phù hợp.','“Nếu chọn growth, chi phí chất lượng nào chấp nhận? Nếu chọn giảm hủy, ảnh hưởng acquisition thế nào?”','Completed services, đặt lại, refund và segmentation theo studio/traffic. Hai hướng có thể hợp lý nếu phù hợp objective và constraints.','Volume tăng không đảm bảo value tăng. Rate và count phải được đọc cùng nhau; chưa có counterfactual để chọn feature.'],
 ['Reminder adoption tăng, no-show tăng','Adoption là sử dụng feature; no-show là outcome. Hai nhóm có thể khác cohort hoặc reminder tập trung ở nhóm rủi ro cao.','“Có thể reminder đã giảm no-show của nhóm dùng nó, trong khi platform tổng thể vẫn tăng no-show không?”','Cùng cohort/window; thời điểm gửi/nhận; nhóm tương đồng; experiment nếu khả thi. Không chia nhóm khác đặc tính rồi kết luận causal.','Correlation không chứng minh feature thất bại. Confidence phải phản ánh evidence của giải pháp.'],
 ['Active studios tăng, onboarding chậm','Supply tăng và friction onboarding có thể cùng tồn tại. Active và activation chưa được định nghĩa đồng nhất.','“Demand có bị thiếu supply không? Studio hiện có có lịch trống? Bước nào làm onboarding chậm?”','Demand/supply theo địa bàn, công suất, time-to-first-booking và breakdown thời gian onboarding.','Priority giữa mở rộng supply và khai thác supply đổi theo context; không dùng target 3 ngày làm mục tiêu mặc định.'],
 ['GMV tăng, tập trung vào studio lớn','Top 20% active studios tạo 63% GMV. Có cả cơ hội thương mại và concentration risk.','“Phục vụ studio lớn tạo value gì? Nếu mất nhóm này thì sao? Đầu tư studio nhỏ có evidence về demand không?”','Contribution và retention theo studio, chi phí phục vụ, switching risk và khả năng tăng trưởng các nhóm.','Không mặc định concentration là xấu. Cần strategic objective và risk appetite trước khi chọn hướng.'],
 ['Tickets và bookings tăng','1.240 tickets/tháng tăng 32%; booking KPI tăng 25,3%. Các baseline/window chưa được xác nhận khớp.','“Team đang so sánh cùng kỳ không? Một booking có nhiều tickets? Category lớn nhất có severity lớn nhất?”','Tickets/100 bookings cùng scope, severity, handling time, repeat contacts và nguyên nhân gốc.','Không suy ra quality giảm chỉ bằng tổng tickets; không tự so hai delta khác baseline.'],
]
export default function FacilitatorGuide() {
 return <div className="space-y-10 text-slate-700"><div className="rounded-2xl bg-slate-950 p-6 text-white"><p className="text-xs uppercase tracking-widest text-blue-300">Facilitator notes</p><h1 className="mt-3 text-3xl font-semibold">Điều phối thảo luận & debrief</h1><p className="mt-4 text-sm leading-7 text-slate-300">Mục tiêu: giúp học viên xây lập luận có context, evidence và trade-off. Không chấm team theo việc chọn cùng initiative với host. Chỉ phát dữ kiện đúng phase; nội dung dưới đây là hướng dẫn dẫn dắt, không thay thế context và capacity đã chốt trong tài liệu workshop.</p></div>
 <nav aria-label="Facilitator sections" className="flex flex-wrap gap-2">{[['fac-dimensions','4. Dimensions'],['fac-tradeoffs','5. Trade-off'],['fac-practice','6. Điều phối']].map(([id,label]) => <a key={id} href={`#${id}`} className="rounded-lg border bg-white px-4 py-2 text-sm">{label}</a>)}</nav>
 <Section id="fac-dimensions" title="4. Hướng dẫn dùng dữ liệu để đánh giá priority">
 <Block title="Mục tiêu học tập & cách mở thảo luận"><p>Học viên phân biệt problem evidence với solution evidence; chọn dimensions phục vụ objective; nêu unknown trước khi chấm score. Có thể sử dụng RICE, WSJF, MoSCoW hoặc framework riêng nếu giải thích được logic và phù hợp input.</p><p><strong>Lời dẫn:</strong> “Chúng ta chưa chọn feature. Hãy xác định outcome cần cải thiện trong context hiện tại, dữ kiện nào hỗ trợ và điều gì vẫn là giả định.” Yêu cầu team viết một observation, ít nhất hai interpretations và một câu hỏi kiểm chứng.</p></Block>
 <Rows heads={['Dimension','Câu hỏi host','Lỗi cần nhận diện','Cách dẫn dắt sửa lập luận']} rows={dimensionRows}/>
 <Block title="Từ dimensions đến framework"><ol className="list-decimal space-y-2 pl-5"><li>Chốt context: objective, window, capacity, constraints. Dùng đúng thông tin phase được phát.</li><li>Chọn dimensions có thể phân biệt các lựa chọn. Ghi định nghĩa và scale trước khi chấm.</li><li>Chọn framework: RICE cần eligible Reach và giả thuyết Impact; WSJF cần Cost of Delay và Job Size nhất quán; MoSCoW cần kiểm tra điều kiện Must bằng hậu quả nếu thiếu; Story Mapping cần luồng người dùng và lát cắt outcome.</li><li>Dùng cùng scale cho mọi initiative; ghi evidence, unknown và dependency. Không cộng hai dimensions cùng đo một giá trị để làm score cao giả tạo.</li><li>Thử sensitivity: nếu Confidence thấp hơn hoặc Effort cao hơn, thứ tự có đổi không? Dùng score để làm rõ lập luận, không biến chênh lệch nhỏ thành quyết định chắc chắn.</li></ol><p><strong>Debrief:</strong> “Priority là quan hệ giữa các lựa chọn trong một context. Framework giúp nhất quán cách nghĩ; độ chính xác của score không vượt quá độ chính xác của input.”</p></Block>
 </Section>
 <Section id="fac-tradeoffs" title="5. Điều phối các tình huống trade-off">
 <Block title="Cách sử dụng tình huống"><p>Chọn tình huống liên quan phase và objective hiện tại. Cho team tách observation / hypothesis / missing evidence, sau đó bảo vệ một hướng lựa chọn và nêu điều phải trì hoãn. Mời team khác đưa một cách giải thích hoặc context khiến lựa chọn đảo chiều.</p><p>Host chỉ tiết lộ gợi ý sau phần trình bày. Đánh giá tính hợp lý của chuỗi evidence → hypothesis → outcome → initiative; không đòi một “đáp án đúng” duy nhất.</p></Block>
 {scenarios.map(([title,reading,question,evidence,debrief]) => <Block key={title} title={title}><p><strong>Cách đọc:</strong> {reading}</p><p><strong>Câu hỏi phản biện:</strong> {question}</p><p><strong>Evidence cần bổ sung / tiêu chí lập luận:</strong> {evidence}</p><p><strong>Debrief:</strong> {debrief}</p></Block>)}
 <Block title="Khi hai team chọn khác nhau"><p>Hỏi lần lượt: có cùng objective không; có cùng window/segment không; giả định Impact có khác không; constraints và risk appetite có khác không? Nếu context giống nhau nhưng lựa chọn khác, yêu cầu chỉ ra evidence hoặc trọng số gây khác biệt.</p><p>Không ép hội tụ sớm. Nếu thiếu dữ kiện quyết định, chấp nhận kết luận có điều kiện và đề nghị bước kiểm chứng đủ nhỏ để giảm uncertainty.</p></Block>
 </Section>
 <Section id="fac-practice" title="6. Runbook, phản biện & đánh giá phần trình bày">
 <Rows heads={['Thời điểm','Host làm gì','Output cần quan sát']} rows={[
 ['Trước workshop','Mở dashboard, thử password và khóa lại; kiểm tra dataset, initiative cards, context từng phase và capacity. Chọn câu hỏi đúng phase; không tự tạo thêm CU hay deadline.','Nguồn dữ kiện nhất quán; học viên mở Dashboard/Hướng dẫn được, notes facilitator đóng.'],
 ['Mở một phase','Đọc objective, timeframe, constraints, dữ kiện mới. Yêu cầu team nói lại context bằng một câu.','Một câu decision context; không lấy target giả định thay cho objective.'],
 ['Team phân tích','Quan sát và hỏi gợi mở; nhắc phân biệt measurement/interpretation. Không chọn initiative hộ team.','Shortlist có evidence, dimensions và unknown; dependency được xét.'],
 ['Team trình bày','Yêu cầu outcome, đối tượng, evidence, assumptions, trade-off và điều kiện đổi quyết định. Mời một team phản biện.','Lập luận có thể kiểm tra; không chỉ đọc score hoặc danh sách feature.'],
 ['Debrief','Nhận xét điểm lập luận được evidence hỗ trợ, chỗ suy luận quá mức và dữ kiện cần kiểm chứng. So sánh cách nghĩ giữa các team.','Team biết vì sao lựa chọn có điều kiện; phân biệt disagreement về context và evidence.'],
 ['Phát dữ kiện tiếp theo','Yêu cầu đánh dấu điều gì đổi: objective, Reach, Impact, Confidence, Urgency, Effort hay dependency.','Bản re-prioritize có giải thích thay đổi và điều giữ nguyên.'],
 ['Kết thúc','Mời team trình bày framework riêng, khi nào dùng và giới hạn. Liên hệ một quyết định thực tế của học viên.','Framework gồm context, dimensions, evidence, decision rule và review trigger.'],
 ]}/>
 <Block title="Mẫu yêu cầu team trình bày"><p>“Trong [context], chúng tôi ưu tiên [initiative] để cải thiện [outcome] cho [segment]. Evidence là [nguồn + giá trị + window]. Giả định cần kiểm chứng là [hypothesis]. Chúng tôi dùng [dimensions/framework] vì [lý do]. Confidence là [mức + căn cứ]. Chấp nhận trì hoãn [lựa chọn khác]. Xem xét lại khi [evidence/context thay đổi].”</p></Block>
 <Rows heads={['Tiêu chí quan sát','Lập luận đủ rõ','Host hỏi thêm khi chưa rõ']} rows={[
 ['Context fit','Outcome, segment, window và constraints rõ; giải thích vì sao initiative phục vụ objective.','Nếu objective đổi thì thứ tự có đổi không?'],
 ['Data literacy','Scope/denominator đúng; phân biệt % và pp; ghi nhận raw data còn thiếu.','Team đang so sánh cùng window và cùng đơn vị không?'],
 ['Causal reasoning & Confidence','Tách observation khỏi hypothesis; có alternative explanation và plan kiểm chứng.','Evidence chứng minh vấn đề hay hiệu quả giải pháp?'],
 ['Trade-off & feasibility','Nêu điều trì hoãn, capacity, dependency và risk.','Nếu chỉ còn nửa capacity, team bỏ gì và vì sao?'],
 ['Consistency & adaptability','Dùng dimensions nhất quán; giải thích sensitivity và review trigger.','Dữ kiện mới nào đủ để team đổi quyết định?'],
 ]}/>
 <Block title="Can thiệp những lỗi thường gặp"><p><strong>Chọn feature theo cảm tính:</strong> hỏi “Observation nào làm team đưa lựa chọn này vào shortlist?”</p><p><strong>Chấm score rất chính xác nhưng input yếu:</strong> hỏi “Nếu score thay đổi một mức, quyết định còn đứng vững không?”</p><p><strong>Chọn mọi thứ là Must:</strong> hỏi “Thiếu initiative này thì lát cắt hiện tại có đạt outcome tối thiểu không? Có workaround không?”</p><p><strong>Coi AI là giải pháp mặc định:</strong> hỏi “Nguyên nhân đã xác minh là gì? Có lựa chọn đơn giản hơn cùng tác động không?”</p><p><strong>Không đổi priority khi context đổi:</strong> hỏi “Team đã cập nhật dimension nào? Lựa chọn giữ nguyên vì evidence hay vì đã cam kết?”</p></Block>
 <Block title="Debrief cuối buổi"><p>“Một quyết định tốt nêu rõ context, sử dụng evidence đúng phạm vi, công khai giả định và chấp nhận trade-off. Khi evidence hoặc context đổi, re-prioritize là phần của quản lý sản phẩm. Chúng ta đánh giá chất lượng reasoning, không chỉ vị trí cuối cùng của feature.”</p><p><strong>Bài chuyển giao:</strong> mỗi học viên chọn một quyết định tại sản phẩm của mình; viết objective, ba observations, hai assumptions, dimensions sử dụng và một review trigger. Không cần áp lại nguyên framework của Hẹn.</p></Block>
 </Section></div>
}
