import {Card,CardContent,CardHeader,CardTitle} from './ui/card'
import {caseContract} from '../lib/data'
function Block({title,children}){return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="space-y-3 text-sm leading-7">{children}</CardContent></Card>}
function Table({heads,rows}){return <div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-100"><tr>{heads.map(h=><th key={h} className="p-4">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t bg-white">{r.map((v,j)=><td key={j} className="p-4 align-top leading-7">{v}</td>)}</tr>)}</tbody></table></div>}
export default function FacilitatorGuide(){return <div className="space-y-8">
 <div className="rounded-2xl bg-slate-950 p-6 text-white"><h1 className="text-3xl font-semibold">Điều phối Buổi 2</h1><p className="mt-4 text-sm leading-7 text-slate-300">Evidence surface → chọn bottleneck → defend → converge → portfolio → reveal dimensions → logic 0.1. Notes dành riêng host; không chiếu trước activity reveal. Nội dung theo Facilitator Guide cập nhật 02.10.2026; không phải một bài giảng data analysis.</p></div>
 <Block title="Khóa case contract"><p>{caseContract.model}</p><p><strong>Parent outcome:</strong> {caseContract.outcome} Không vote lại outcome công ty. Team đề xuất bottleneck/sub-objective, cả lớp converge rồi tự chọn portfolio theo shared objective.</p><p><strong>Boundary:</strong> 20 CU mới / 6 tuần; không tăng nhân sự vận hành hoặc ngân sách thu hút khách. CU không quy đổi ra giờ/tuần. H01/H02/H04/H05/H08 basic đã chạy; H03/H07/H10 nâng cao/H12/H19 chưa có. Thẻ Phase 2 tính scope mới. H05 basic chưa reminder.</p><p>Đây là trạng thái chung sau ba tháng, không phải kết quả MVP mỗi team. Pilot Buổi 1 12 studios/8 tuần không giới hạn total studios Buổi 2. Total registered chưa biết; không cộng 48 và 72.</p><p>Phí Hẹn 8% completed-service value; 300.000 ₫ chỉ tham chiếu. Seats hủy/no-show chưa hoàn thành; booking created không phải completed service. Revenue, booked GMV và profit khác nhau.</p></Block>
 <section className="space-y-4"><h2 className="text-xl font-semibold">4. Evidence → dimensions, chỉ reveal đúng lúc</h2><Block title="Đọc dashboard trước khi chọn feature"><p>Cho team 12–15 phút ghi ba bottlenecks: observation, nguồn, liên hệ tới completed seats, điều chưa biết. Không yêu cầu root cause hoàn chỉnh hoặc tính score. Nếu học viên sa vào phép tính, hỏi: “Kết quả đó thay đổi quyết định nào?”</p><p>P2-A/B/C ngang cấp. H03 không tự cứu cả 48; 90 chỗ liên quan cập nhật muộn không phải 90 recoverable; 9/72 mở H04 không chứng minh ít value. Trend, funnel, giá và tickets là synthetic bổ sung, không đổi nguồn thành thẻ gốc.</p></Block>
 <Table heads={['Câu học viên nói','Dimension reveal sau portfolio','Host làm rõ']} rows={[
 ['Nhiều người gặp','Reach','Cùng unit/window; chỉ eligible segment. Không cộng studios, seats, customers; total 72 chỉ là tập đo H04.'],
 ['Thay đổi việc tham gia','Impact','Chuỗi tác động tới completed seats. Observation về problem không dự báo uplift feature. Không đổi parent outcome thành revenue/retention/support.'],
 ['Chưa chắc feature giúp','Confidence','Độ chắc về solution khác độ chắc problem tồn tại. Nêu hypothesis, evidence cần kiểm chứng; không chấm nhãn High/Medium/Low hộ team.'],
 ['Làm tốn nguồn lực','Effort','Dùng CU scope mới của thẻ Phase 2 và dependency. Không đổi manual handling time thành engineering estimate.']
 ]}/>
 <Block title="Logic 0.1 và mapping cuối buổi"><p>Sau portfolio và so sánh reasoning, rút câu hỏi học viên đã nói rồi mới gọi tên dimensions. Team chọn tối đa bốn dimensions, ghi nghĩa theo shared objective, evidence để so và rule “Khi A/B cạnh tranh, ưu tiên…, trừ khi…”. Không ép đủ bốn; không cấp trọng số mặc định.</p><p>Áp rule lên hai initiatives thật. Nếu rule khác portfolio, sửa rule hoặc decision và giải thích; không sửa điểm để bảo vệ lựa chọn cũ. Context → Objective → Dimensions → Framework → Decision; evidence/constraints xuyên suốt.</p><p>Mapping: Impact-Effort cần axes cùng nghĩa. Câu hỏi RICE bằng lời: ai hưởng lợi, hành vi đổi thế nào, bằng chứng chắc đến đâu, CU/dependency nào? Chưa tính RICE score. Không giảng trước toàn bộ taxonomy của các buổi sau.</p></Block></section>
 <section className="space-y-4"><h2 className="text-xl font-semibold">5. Debate, trade-off và convergence</h2><Table heads={['Vùng evidence','Câu challenge','Điểm debrief / unknown']} rows={[
 ['P2-A: 48 = 28 + 20','Hồ sơ hay tạo lịch đang cản trở? Nếu mở bán được thì demand từ đâu?','Phân biệt duyệt hồ sơ và mở lịch. H03 vẫn cần người duyệt; 20 studio đã duyệt không nhất thiết cần tự điền hồ sơ. Chưa biết demand.'],
 ['P2-B: 180 / 90 seats','Liên quan cập nhật muộn do software hay quy trình? Ai đủ điều kiện H12?','Không suy ra cứu được 90. Điều kiện đổi một lần/cùng hoạt động-giá/còn chỗ/ít nhất 24 giờ chưa có số eligibility. Questions tìm vé và đổi buổi khác nhau.'],
 ['P2-C: 9/72 H04','Ít mở do thiếu value, khó tìm/khó dùng hay email đã đủ? Báo cáo nối completed seats thế nào?','Interview khác behavior. Không coi dashboard workshop là H04; không tự giả định thêm report features sẽ đổi outcome.'],
 ['Synthetic trend: completed seats và revenue tăng','Bottleneck nào vẫn cản outcome? Guardrail nào không được làm xấu?','Tăng trưởng chung không phủ nhận friction. Cancellation không thắng mặc định; team phải nối lựa chọn vào outcome và demand hiện có.'],
 ['Synthetic support counts/minutes','Nhóm ticket lớn có nghĩa là nhóm cần ưu tiên nhất?','Cần severity, nguyên nhân và contribution tới outcome. Không có rate theo booking hoặc eligibility. Không thêm manual work nếu không nêu việc giảm bớt/rollout giới hạn.']
 ]}/>
 <Block title="Ba vòng defend / challenge"><p>Mỗi vòng 5 phút: 2 phút pitch, 2 phút team kế challenge, 1 phút trả lời. A được B challenge, B được C, C được A; host dành 2 phút tổng hợp trong block debate 18 phút. Hỏi: problem hay solution evidence; causal link tới completed seats; vì sao trước bottleneck khác; assumption nào đảo chiều?</p><p>Giữ dissent. Hai hướng đều có thể hợp lý trước convergence, nhưng sau khi chốt shared sub-objective, portfolio phải đóng góp vào hướng chung. Không ép chọn cancellation vì host thích.</p></Block>
 <Block title="Converge trong 8 phút"><p>5 phút: làm rõ candidates, mỗi người chọn một hướng kèm lý do. Hòa: mỗi bên 30 giây, vote lại; vẫn hòa host chốt và ghi lý do. 3 phút: khóa metric/guardrail, baseline, timebox, backlog. Vote là cơ chế vận hành, không thay evidence.</p><p>Decision card: “Chọn [sub-objective] vì [reason]. Dissent [điều cần lưu]. Review nếu [signal].” Parent outcome giữ nguyên. Nếu objective là “xây H12”, hỏi thay đổi hành vi/kết quả cần đạt là gì.</p></Block></section>
 <section className="space-y-4"><h2 className="text-xl font-semibold">6. Runbook, portfolio và debrief</h2><Table heads={['Phút trong 115 phút','Hoạt động','Output']} rows={[
 ['0–8','Recap MVP','Quyết định/trade-off thật từng team; không gán đáp án MVP.'],
 ['8–15','Baseline','Shared state, parent outcome, 20 CU/6 tuần.'],
 ['15–30','Dashboard','Ba bottlenecks, evidence, causal link và unknown.'],
 ['30–35','Objective','Bottleneck/sub-objective mỗi team.'],
 ['35–53','Debate','Ba vòng defend/challenge; ghi dissent.'],
 ['53–61','Converge','Shared sub-objective, metric/guardrail và boundary.'],
 ['61–76','Portfolio','Mã/scope, thứ tự, Top 3, CU, dependency, hai trade-off.'],
 ['76–84','So sánh','Khác biệt trong reasoning, không chỉ feature list.'],
 ['84–92','Dimensions','Rút câu hỏi rồi gọi tên; không reveal trước.'],
 ['92–100','Logic 0.1','Tối đa bốn dimensions, rule, kiểm tra hai initiatives.'],
 ['100–108','Mapping','Impact-Effort và câu hỏi RICE bằng lời.'],
 ['108–115','Debrief & snapshot','Portfolio chưa triển khai; lưu bàn giao.']
 ]}/>
 <Block title="Acceptance của portfolio"><p>Tổng CU ≤20, dùng scope/CU Phase 2. Top 3 để trình bày sâu, không giới hạn portfolio chỉ ba initiatives; không bắt dùng hết CU. Không tự tạo scope nhỏ hơn hay estimate mới.</p><p>Nêu dependency/workaround, hai giá trị chấp nhận trì hoãn, assumption chính, owner/mốc/trigger review. H08/H10 được chọn nếu nối được parent outcome. Mọi xử lý thủ công thêm phải nêu việc giảm bớt hoặc giới hạn rollout.</p><p>Mỗi team 2 phút: initiative đầu tiên, một trade-off, assumption đảo quyết định. So nguồn khác biệt: nhóm hưởng lợi, thay đổi kỳ vọng, tin solution đến đâu, CU/dependency. Không chấm theo mức giống portfolio mẫu.</p></Block>
 <Table heads={['Tiêu chí host','Đủ rõ','Câu hỏi nếu thiếu']} rows={[
 ['Objective rõ','Nối sub-objective với completed seats và demand hiện có','Nếu thành công, hành vi tham gia nào đổi?'],
 ['Căn cứ đúng','Đúng nguồn, unit, window; tách problem/solution','90 nói về liên quan hay khả năng phục hồi?'],
 ['Khả thi','CU≤20, dependencies, không tăng staffing/acquisition budget','Việc thủ công thêm được bù bằng việc giảm gì?'],
 ['Trade-off cụ thể','Giá trị trì hoãn và lý do','Hoãn phương án B mất điều gì, cho nhóm nào?'],
 ['Review có điều kiện','Assumption, owner/mốc và signal đổi quyết định','Nếu evidence này sai, team đổi lựa chọn nào?']
 ]}/>
 <Block title="Debrief cuối buổi"><p>“Priority là tương quan các lựa chọn trong context. Evidence về problem khác evidence về solution. Một logic tốt nêu outcome, căn cứ, feasibility, trade-off và review; chưa cần score đầy đủ.”</p><p>Lưu snapshot cuối Buổi 2: shared sub-objective, portfolio/scope/CU, hai trade-off, assumptions, owner/mốc/trigger review, logic 0.1. Portfolio mới là quyết định planning, chưa được triển khai. Giữ notes và các context của buổi sau ngoài student screen.</p></Block></section>
 </div>}
